#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ,               sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393TurboSpeed_MC29, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port9,           rightMotor,    tmotorVex393TurboSpeed_MC29, openLoop, reversed, driveRight, encoderPort, dgtl3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ChRX Ch1
#define ChRY Ch2
#define ChLY Ch3
#define ChLX Ch4

#define ARCADE_BTN Btn8U
#define REVERSED_BTN Btn8D
#define SPLIT_BTN Btn8L

#define NUM_STORE Btn8R

#define STICK_THRESH 15

#define STORE_MAX 10

#define HOLONOMIC

typedef struct {
	float encVal,
		valLast,
		time,
		timeLast,
		deltaEnc,
		deltaLast,
		accel,
		savedVals[STORE_MAX];
	tSensors name;
	bool reversed;
} Encoder;

#ifdef HOLONOMIC
Encoder flEnc,
	frEnc,
	blEnc,
	brEnc;
#else
Encoder lEnc,
	rEnc;
#endif

void updateEnc(Encoder *enc) {
	enc->valLast = enc->encVal;
	enc->timeLast = enc->time;
	enc->deltaLast = 1.0 * enc->deltaEnc;
	
	enc->encVal = SensorValue[enc->name];
	enc->time = nPgmTime;
	
	enc->deltaEnc = 1.0 * (enc->encVal - enc->valLast) / (enc->time - enc->timeLast);
	
	enc->accel = 1.0 * (enc->deltaEnc - enc->deltaLast) / (enc->time - enc->timeLast);
}

void saveEncVal(Encoder *enc) {
	enc->savedVals[enc->saveCount] = enc->encVal;
}

task main() {
	int rx,
		ry,
		lx,
		ly,
		saveCount;
#ifndef HOLONOMIC
	bool arcade,
		split,
		reversed;
#endif

#ifdef HOLONOMIC
	word storeLast;
#else
	word arcadeLast,
		splitLast,
		reversedLast,
		storeLast;
#endif

#ifdef HOLONOMIC
flEnc.name = flWheelEnc;
frEnc.name = frWheelEnc;
blEnc.name = blWheelEnc;
brEnc.name = brWheelEnc;
#else
lEnc.name = lWheelEnc;
rEnc.name = rWheelEnc;
#endif


	while(true) {
		rx = (abs(vexRT[ChRX]) > STICK_THRESH) ? vexRT[ChRX] : 0;
		ry = (abs(vexRT[ChRY]) > STICK_THRESH) ? vexRT[ChRY] : 0;
		ly = (abs(vexRT[ChLY]) > STICK_THRESH) ? vexRT[ChLY] : 0;
		lx = (abs(vexRT[ChLX]) > STICK_THRESH) ? vexRT[ChLX] : 0;

#ifdef HOLONOMIC
		updateEnc(&flEnc);
		updateEnc(&frEnc);
		updateEnc(&blEnc);
		updateEnc(&brEnc);
#else
		updateEnc(&lEnc);
		updateEnc(&rEnc);
#endif

#ifdef HOLONOMIC
    motor[flWheel] = ly + rx + lx;
    motor[frWheel] = ly - rx - lx;
    motor[blWheel] = ly + rx - lx;
    motor[brWheel] = ly - rx + lx;
#else
		if(vexRT[ARCADE_BTN] != arcadeLast) {
			arcadeLast = vexRT[ARCADE_BTN];
			arcade = !arcade;
		}

		if(vexRT[SPLIT_BTN] != splitLast) {
			splitLast = vexRT[SPLIT_BTN];
			split = !split;
		}

		if(vexRT[REVERSED_BTN] != reversedLast) {
			reversedLast = vexRT[REVERSED_BTN];
			reversed = !reversed;
		}


		if(arcade) {
			if(split) {
				motor[leftMotor] = reversed ? rx - ly : ly + rx;

				motor[rightMotor] = reversed ? -ly - rx : ly - rx;
			}

			else {
				motor[leftMotor] = reversed ? lx - ly : ly + lx;

				motor[rightMotor] = reversed ? -ly - lx : ly - lx;
			}
		}

		else {
			motor[leftMotor] = reversed ? -ry : ly;
			motor[rightMotor] = reversed ? -ly : ry;
		}
#endif

		if(vexRT[NUM_STORE] != storeLast) {
			storeLast = vexRT[NUM_STORE];
			
			if(storeCount < STORE_MAX) {
#ifdef HOLONOMIC
				saveEncVal(&flEnc);
				saveEncVal(&frEnc);
				saveEncVal(&blEnc);
				saveEncVal(&brEnc);
#else
				saveEncVal(&lEnc);
				saveEncVal(&rEnc);
#endif
			}
			
		}

		wait1Msec(20);
	}
}
